---
version: "3"
services:
  # GENESIG
  genesis-abci:
    hostname: genesis-abci
    image: roongr2k7/abci:0.1.0
    command: /abci-server 0.0.0.0:46000
    environment:
      - CALLBACK_URI=
    expose:
      - "46000"
    networks:
      - tendermint-net

  genesis-tendermint:
    hostname: genesis-tendermint
    image: roongr2k7/tendermint:0.16.0
    entrypoint: /tmp/scripts/init-tendermint.sh
    command: /tmp/scripts/start-tendermint.sh --proxy_app=tcp://genesis-abci:46000
    depends_on:
      - genesis-abci
    networks:
      - tendermint-net
    volumes:
      - ./tendermint:/tendermint
      - ./scripts:/tmp/scripts


  # AS
  as-abci:
    #hostname: as-abci
    image: roongr2k7/abci:0.1.0
    command: /abci-server 0.0.0.0:46000
    environment:
      - CALLBACK_URI=
    expose:
      - "46000"
    networks:
      - tendermint-net

  as-tendermint:
    #hostname: as-tendermint
    image: roongr2k7/tendermint:0.16.0
    entrypoint: /tmp/scripts/init-tendermint.sh
    command: /tmp/scripts/start-tendermint.sh --proxy_app=tcp://as-abci:46000
    networks:
      - tendermint-net
    volumes:
      - ./tendermint:/tendermint
      - ./scripts:/tmp/scripts
    depends_on:
      - genesis-tendermint
      - as-abci


  # IdP
  idp-abci:
    #hostname: idp-abci
    image: roongr2k7/abci:0.1.0
    command: /abci-server 0.0.0.0:46000
    environment:
      - CALLBACK_URI=
    expose:
      - "46000"
    networks:
      - tendermint-net

  idp-tendermint:
    #hostname: idp-tendermint
    image: roongr2k7/tendermint:0.16.0
    entrypoint: /tmp/scripts/init-tendermint.sh
    command: /tmp/scripts/start-tendermint.sh --proxy_app=tcp://idp-abci:46000
    networks:
      - tendermint-net
    volumes:
      - ./tendermint:/tendermint
      - ./scripts:/tmp/scripts
    depends_on:
      - genesis-tendermint
      - idp-abci


  #RP
  rp-abci:
    #hostname: rp-abci
    image: roongr2k7/abci:0.1.0
    command: /abci-server 0.0.0.0:46000
    environment:
      - CALLBACK_URI=
    expose:
      - "46000"
    networks:
      - tendermint-net

  rp-tendermint:
    #hostname: rp-tendermint
    image: roongr2k7/tendermint:0.16.0
    entrypoint: /tmp/scripts/init-tendermint.sh
    command: /tmp/scripts/start-tendermint.sh --proxy_app=tcp://rp-abci:46000
    networks:
      - tendermint-net
    volumes:
      - ./tendermint:/tendermint
      - ./scripts:/tmp/scripts
    depends_on:
      - genesis-tendermint
      - rp-abci

networks:
  tendermint-net:
